import type { PilotInput } from './db';

type SeedPilot = Pick<PilotInput, 'firstName' | 'lastName' | 'rank'> & { licenseExpiry?: string };

// Commandants de bord (CDB) 737NG — issus du classement professionnel définitif
// CDB année 2026 (pilotes cochés au stylo par Fleet Training).
const CAPTAINS: SeedPilot[] = [
  { lastName: 'Benbetka', firstName: 'Nadjib-Mohamed', rank: 'CDB', licenseExpiry: '2026-07-05' },
  { lastName: 'Bousmal', firstName: 'Zinedine', rank: 'CDB' },
  { lastName: 'Benseghir', firstName: 'Abdelkrim', rank: 'CDB' },
  { lastName: 'Hamza', firstName: 'Abdelmadjid', rank: 'CDB' },
  { lastName: 'Dakhli', firstName: 'Mahmoud', rank: 'CDB', licenseExpiry: '2026-08-19' },
  { lastName: 'Bachtarzi', firstName: 'Karim', rank: 'CDB' },
  { lastName: 'Teggari', firstName: 'Abdelwaheb', rank: 'CDB' },
  { lastName: 'Derouiche', firstName: 'Tarik-Rabah', rank: 'CDB' },
  { lastName: 'Bouachiba', firstName: 'Lakhdar', rank: 'CDB' },
  { lastName: 'Drider', firstName: 'Habib', rank: 'CDB' },
  { lastName: 'Bouhelassa', firstName: 'Abdelhafid', rank: 'CDB', licenseExpiry: '2026-08-11' },
  { lastName: 'Malki', firstName: 'Lounes', rank: 'CDB' },
  { lastName: 'Djoudi', firstName: 'Djamal', rank: 'CDB' },
  { lastName: 'Annane', firstName: 'Azeddine', rank: 'CDB' },

  { lastName: 'Laliki', firstName: 'Mohamed', rank: 'CDB' },
  { lastName: 'Zagai', firstName: 'Noureddine', rank: 'CDB' },
  { lastName: 'Chelli', firstName: 'Mouloud', rank: 'CDB' },
  { lastName: 'Bensaber', firstName: 'Amine-Mohamed', rank: 'CDB' },
  { lastName: 'Bouteflika', firstName: 'Sofiane-Mehdi', rank: 'CDB' },
  { lastName: 'Zerrouati', firstName: 'Abdelhakim', rank: 'CDB' },
  { lastName: 'Ounis', firstName: 'Malek', rank: 'CDB' },
  { lastName: 'Dabbagh', firstName: 'Firas', rank: 'CDB' },
  { lastName: 'Chelfaoui', firstName: 'Madjid', rank: 'CDB' },
  { lastName: 'Hasbellaoui', firstName: 'Raouf', rank: 'CDB' },
  { lastName: 'Iddir', firstName: 'Salem', rank: 'CDB' },
  { lastName: 'El-Amraoui', firstName: 'Khaled', rank: 'CDB' },
  { lastName: 'Zedmia', firstName: 'Maya-Djazia', rank: 'CDB' },
  { lastName: 'Miloudi', firstName: 'Mohamed-Islam', rank: 'CDB' },

  { lastName: 'Meraghni', firstName: 'Rabie', rank: 'CDB' },
  { lastName: 'Issiakhem', firstName: 'Karim-Thierry', rank: 'CDB' },
  { lastName: 'Boudiaf', firstName: 'Mehdi', rank: 'CDB' },
  { lastName: 'Chefirat', firstName: 'Karim', rank: 'CDB' },
  { lastName: 'Rebiai', firstName: 'Dounya', rank: 'CDB' },
  { lastName: 'Lazizi', firstName: 'Kamel', rank: 'CDB' },
  { lastName: 'Ben-Brahim', firstName: 'Mohamed', rank: 'CDB' },
  { lastName: 'Hadjadj-Aoul', firstName: 'Khalid', rank: 'CDB' },
  { lastName: 'Tebbi', firstName: 'Sabrina', rank: 'CDB' },
  { lastName: 'Laadjal', firstName: 'Radhia', rank: 'CDB' },
  { lastName: 'Kheddouci', firstName: 'Soufienne', rank: 'CDB' },
  { lastName: 'Bouchaita', firstName: 'Hocine', rank: 'CDB', licenseExpiry: '2026-07-31' },
  { lastName: 'Skander', firstName: 'Mohamed-Reda', rank: 'CDB' },
  { lastName: 'Ferr', firstName: 'Ilhem', rank: 'CDB' },
  { lastName: 'Bouchenafa', firstName: 'Mohamed-Amine', rank: 'CDB', licenseExpiry: '2026-07-31' },
  { lastName: 'Benzian', firstName: 'Tewfik-Fawzi', rank: 'CDB' },
  { lastName: 'Chelli', firstName: 'Hayet', rank: 'CDB' },
  { lastName: 'Derbal', firstName: 'Amine', rank: 'CDB' },
  { lastName: 'Larbi', firstName: 'Mohamed-Amine', rank: 'CDB' },
  { lastName: 'Gouaref', firstName: 'Hichem', rank: 'CDB' },
  { lastName: 'Oulmane', firstName: 'Tewfik', rank: 'CDB', licenseExpiry: '2026-08-09' },

  { lastName: 'Cherifi', firstName: 'Ouali-Zoheir', rank: 'CDB' },
  { lastName: 'Benasla', firstName: 'Tewfik', rank: 'CDB' },
  { lastName: 'Benbouaziz', firstName: 'Amine', rank: 'CDB' },
  { lastName: 'Annad', firstName: 'Yacine', rank: 'CDB' },
  { lastName: 'Terai', firstName: 'Sofiane', rank: 'CDB' },
  { lastName: 'Rebbouh', firstName: 'Mohamed-Amin', rank: 'CDB' },
  { lastName: 'Balit', firstName: 'Salim', rank: 'CDB' },
  { lastName: 'Ledjedel', firstName: 'Nassim', rank: 'CDB' },
  { lastName: 'Hanafi', firstName: 'Akram', rank: 'CDB' },
  { lastName: 'Abdelbaki', firstName: 'Dalil', rank: 'CDB' },
  { lastName: 'Atia', firstName: 'Oussama', rank: 'CDB' },
  { lastName: 'Mir', firstName: 'Abdellatif', rank: 'CDB' },
  { lastName: 'Driche', firstName: 'Mourad', rank: 'CDB' },
  { lastName: 'El-Amraoui', firstName: 'Tarek', rank: 'CDB' },
  { lastName: 'Zabchi', firstName: 'Yacine', rank: 'CDB' },
  { lastName: 'Guemari', firstName: 'Nissem', rank: 'CDB' },
  { lastName: 'Boukhalfa', firstName: 'Nacer-Eddine', rank: 'CDB' },
  { lastName: 'Otmane', firstName: 'Ahmed-Lyes', rank: 'CDB' },
  { lastName: 'Hamadouche', firstName: 'Mohamed-Nassim', rank: 'CDB' },
  { lastName: 'Ghezali', firstName: 'Ahmed', rank: 'CDB' },
  { lastName: 'Boutaleb', firstName: 'Abdelkader', rank: 'CDB' },
  { lastName: 'Aimeur', firstName: 'Mohamed-Lamine', rank: 'CDB' },
  { lastName: 'Atia', firstName: 'Zakaria', rank: 'CDB' },
  { lastName: 'Ferhat', firstName: 'Mahdi', rank: 'CDB', licenseExpiry: '2026-07-04' },
  { lastName: 'Hamici', firstName: 'Mounir', rank: 'CDB' },
  { lastName: 'Boukrif', firstName: 'Leila', rank: 'CDB' },
  { lastName: 'Moussaoui', firstName: 'Adel', rank: 'CDB' },
  { lastName: 'Boulanouar', firstName: 'Mohamed-Aboubakeur', rank: 'CDB' },
  { lastName: 'Aouissi', firstName: 'Melissa', rank: 'CDB', licenseExpiry: '2026-07-31' },
  { lastName: 'Mohammedi', firstName: 'Walid', rank: 'CDB' },
  { lastName: 'Besbaci', firstName: 'Mehdi', rank: 'CDB' },
  { lastName: 'Kermia', firstName: 'Yacine', rank: 'CDB' },
  { lastName: 'Hafiz', firstName: 'Sharif-Zerrouk', rank: 'CDB' },
  { lastName: 'Lalouani', firstName: 'Mohammed-El-Akram', rank: 'CDB' },
  { lastName: 'Houas', firstName: 'Riadh', rank: 'CDB' },
  { lastName: 'Benlalam', firstName: 'Hicham', rank: 'CDB' },
  { lastName: 'Saidi', firstName: 'Adel', rank: 'CDB' },
  { lastName: 'Berrazouane', firstName: 'Chafik', rank: 'CDB' },
  { lastName: 'Afif', firstName: 'Adel', rank: 'CDB' },
  { lastName: 'Bensenouci', firstName: 'Abdesselam-Fawzi', rank: 'CDB' },
  { lastName: 'Metref', firstName: 'Mounir', rank: 'CDB' },
  { lastName: 'Benbouali', firstName: 'Ryad', rank: 'CDB' },
  { lastName: 'Touimer', firstName: 'Mohamed', rank: 'CDB' },
  { lastName: 'Rekibi', firstName: 'Seddik', rank: 'CDB' },
  { lastName: 'Berkani', firstName: 'Ali', rank: 'CDB' },
  { lastName: 'Mezimez', firstName: 'Messaouda', rank: 'CDB' },
  { lastName: 'Bouziri', firstName: 'Feryal-Fifi', rank: 'CDB' },
  { lastName: 'Boubekeur', firstName: 'Yacine', rank: 'CDB' },

  { lastName: 'Benouis', firstName: 'Mohammed-Fethi', rank: 'CDB' },
  { lastName: 'Terki', firstName: 'Omar-Nabil', rank: 'CDB' },
  { lastName: 'Benmiloud', firstName: 'Amine', rank: 'CDB' },
  { lastName: 'Belkham', firstName: 'Adel', rank: 'CDB' },
  { lastName: 'Aroua', firstName: 'Mohamed-Bilal', rank: 'CDB' },
  { lastName: 'Medkour', firstName: 'Elmoatassem', rank: 'CDB' },
  { lastName: 'Doumi', firstName: 'Youssef-Karim', rank: 'CDB' },
  { lastName: 'Hammoudi', firstName: 'Karim', rank: 'CDB' },
  { lastName: 'Trabzi', firstName: 'Mohamed', rank: 'CDB' },
  { lastName: 'Bouras', firstName: 'Mansour', rank: 'CDB' },
  { lastName: 'Bourradou', firstName: 'Redouane', rank: 'CDB', licenseExpiry: '2026-07-31' },
  { lastName: 'Ghobrini', firstName: 'Abdelghani', rank: 'CDB' },
  { lastName: 'Djermani', firstName: 'Mounir', rank: 'CDB' },
  { lastName: 'Chebout', firstName: 'Salim', rank: 'CDB', licenseExpiry: '2026-07-31' },
  { lastName: 'Mehenni', firstName: 'Feriel', rank: 'CDB' },
  { lastName: 'Daoud', firstName: 'Mohamed-Amine', rank: 'CDB' },
  { lastName: 'Rahal', firstName: 'Hadi-Aniss', rank: 'CDB' },
  { lastName: 'Bousbah', firstName: 'Abdelkrim', rank: 'CDB' },
  { lastName: 'Diafat', firstName: 'Abdelkader', rank: 'CDB' },
  { lastName: 'Arifi', firstName: 'Oussama', rank: 'CDB', licenseExpiry: '2026-08-18' },
  { lastName: 'Meziani', firstName: 'Mouloud', rank: 'CDB' },
  { lastName: 'Orif', firstName: 'Rachid', rank: 'CDB' },
  { lastName: 'Bidi', firstName: "M'Hamed", rank: 'CDB' },
  { lastName: 'Amira', firstName: 'Chakib', rank: 'CDB' },
  { lastName: 'Aliouèche', firstName: 'Nacim', rank: 'CDB' },
  { lastName: 'Sahli', firstName: 'Youcef', rank: 'CDB' },
  { lastName: 'Semidaa', firstName: 'Yacine', rank: 'CDB' },
  { lastName: 'Arroudj', firstName: 'Ali-Sabri', rank: 'CDB' },
  { lastName: 'Bekralas', firstName: 'Cherine', rank: 'CDB' },
  { lastName: 'Belkacem', firstName: 'Mohamed-Tewfik', rank: 'CDB' },
  { lastName: 'Mesloub', firstName: 'Khelifa-Tarik', rank: 'CDB' },
  { lastName: 'Lounis', firstName: 'Abdesselem', rank: 'CDB' },
  { lastName: 'Missaoui', firstName: 'Ala-Eddine', rank: 'CDB' },
  { lastName: 'Chachoua', firstName: 'Mohamed-Riadh', rank: 'CDB', licenseExpiry: '2026-06-03' },
  { lastName: 'Saidi', firstName: 'Sofiane', rank: 'CDB' },
  { lastName: 'Mesli', firstName: 'Mohamed-Riadh', rank: 'CDB' },
  { lastName: 'Ait-Hamou', firstName: 'Yougourthene', rank: 'CDB' },
  { lastName: 'Benhama', firstName: 'Yacine', rank: 'CDB' },
  { lastName: 'Azzouz', firstName: 'Mounir', rank: 'CDB' },
  { lastName: 'Sahnoun', firstName: 'Mohamed-Islam', rank: 'CDB' },
  { lastName: 'Tifoura', firstName: 'Mohamed', rank: 'CDB' },
  { lastName: 'Hamdi-Pacha', firstName: 'Madih', rank: 'CDB' },
  { lastName: 'Abbout', firstName: 'Hilal', rank: 'CDB' },
  { lastName: 'Akli', firstName: 'Fahim', rank: 'CDB' },
  { lastName: 'Braham-Chaouche', firstName: 'Salim', rank: 'CDB' },
  { lastName: 'Benbouaziz', firstName: 'Samy', rank: 'CDB' },
  { lastName: 'Saadouni', firstName: 'Faiz', rank: 'CDB' },
  { lastName: 'Medjamia', firstName: 'Smail', rank: 'CDB' },

  { lastName: 'Nacer-Bey', firstName: 'Mahrez', rank: 'CDB' },
  { lastName: 'Akrour', firstName: 'Zineb', rank: 'CDB' },
  { lastName: 'Bensadi', firstName: 'Redouane', rank: 'CDB' },
  { lastName: 'Khelifa', firstName: 'Sofiane', rank: 'CDB' },
  { lastName: 'Dib', firstName: 'Lotfi', rank: 'CDB' },
  { lastName: 'Ouaguenouni', firstName: 'Amine El-Mahdi', rank: 'CDB' },
  { lastName: 'Benmansour', firstName: 'Lahcene-Riad', rank: 'CDB' },
  { lastName: 'Lamdjadani', firstName: 'Sarah-Loubna', rank: 'CDB' },
  { lastName: 'Lekkal', firstName: 'Mehdi-Redouane', rank: 'CDB', licenseExpiry: '2026-07-31' },
  { lastName: 'Rida', firstName: 'Badis', rank: 'CDB' },
  { lastName: 'Saidane', firstName: 'Khalil', rank: 'CDB', licenseExpiry: '2026-07-26' },
  { lastName: 'Hachemi', firstName: 'Amir', rank: 'CDB', licenseExpiry: '2026-07-31' },
  { lastName: 'Messad', firstName: 'Amir-Khane', rank: 'CDB' },
  { lastName: 'Mokrane', firstName: 'Mohamed-Cherif', rank: 'CDB' },
  { lastName: 'Aggoun', firstName: 'Ahmed-Kheireddine', rank: 'CDB' },
  { lastName: 'Bencharif', firstName: 'Yacine-Reza', rank: 'CDB', licenseExpiry: '2026-08-25' },
  { lastName: 'Hadj-Mehdi', firstName: 'Samy', rank: 'CDB' },
  { lastName: 'Tobni', firstName: 'Mohamed Amine', rank: 'CDB' },
  { lastName: 'Rechache', firstName: 'Abdelhamid', rank: 'CDB' },
  { lastName: 'Hachouf', firstName: 'Mohamed Amine', rank: 'CDB' },
  { lastName: 'Graine', firstName: 'Mohammed Amine', rank: 'CDB' },
  { lastName: 'Boucenna', firstName: 'Riadh', rank: 'CDB' },
  { lastName: 'Boucenna', firstName: 'Lyes', rank: 'CDB' },

  { lastName: 'Ramdane', firstName: 'Sofiane', rank: 'CDB' },

  // Confirmés 737NG par le PDF SECTEUR_NG (licence déjà expirée/proche) alors
  // qu'ils n'avaient pas été repérés comme cochés sur la photo du classement CDB.
  { lastName: 'Louni', firstName: 'Heddi', rank: 'CDB', licenseExpiry: '2026-08-17' }
];

// Officiers pilotes de ligne (OPL) 737NG — issus du classement professionnel
// définitif FO année 2026 (pilotes cochés au stylo par Fleet Training).
const FIRST_OFFICERS: SeedPilot[] = [
  { lastName: 'Hammouda', firstName: 'Rhym', rank: 'OPL' },
  { lastName: 'Tireche', firstName: 'Mouad', rank: 'OPL' },
  { lastName: 'Kassa', firstName: 'Yacine', rank: 'OPL', licenseExpiry: '2026-07-31' },
  { lastName: 'Berkane', firstName: 'Mahiddine', rank: 'OPL', licenseExpiry: '2026-07-31' },
  { lastName: 'Saadi', firstName: 'Ouahida', rank: 'OPL' },
  { lastName: 'Bentoumi', firstName: 'Wally', rank: 'OPL' },
  { lastName: 'Chenguel', firstName: 'Zohra', rank: 'OPL' },
  { lastName: 'Karfa', firstName: 'Hichem', rank: 'OPL', licenseExpiry: '2026-08-19' },
  { lastName: 'Mebrouk', firstName: 'Omar', rank: 'OPL' },
  { lastName: 'Saber Cherif', firstName: 'Nabil', rank: 'OPL', licenseExpiry: '2026-08-27' },
  { lastName: 'Kaddour', firstName: 'Mohamed Nazim', rank: 'OPL' },
  { lastName: 'Naimi', firstName: 'Djaafar', rank: 'OPL' },
  { lastName: 'Badri', firstName: 'Abdellah', rank: 'OPL' },
  { lastName: 'Abbad', firstName: 'Abdelkader', rank: 'OPL' },

  { lastName: 'Boucemina', firstName: 'Abderrahim', rank: 'OPL' },
  { lastName: 'Remil', firstName: 'Zakaria', rank: 'OPL' },
  { lastName: 'Belouanas', firstName: 'Abdelmoumin', rank: 'OPL' },
  { lastName: 'Benali', firstName: 'Mohamed Rafik', rank: 'OPL' },
  // Prénoms corrigés d'après le PDF SECTEUR_NG (source typographiée, plus fiable
  // que la lecture des coches manuscrites) : Meliani/Zerrouki étaient inversés.
  { lastName: 'Meliani', firstName: 'Nassim', rank: 'OPL' },
  { lastName: 'Zerrouki', firstName: 'Imad-Eddine', rank: 'OPL', licenseExpiry: '2026-07-31' },
  { lastName: 'Touchen', firstName: 'Nezzar Mohamed Lamine', rank: 'OPL' },
  { lastName: 'Labbaci', firstName: 'Mounir', rank: 'OPL' },
  { lastName: 'Chemmi', firstName: 'Seifeddine', rank: 'OPL' },
  { lastName: 'Ghriss', firstName: 'Mohammed Sallah Eddine', rank: 'OPL' },
  { lastName: 'Midoune', firstName: 'Meziane', rank: 'OPL' },
  { lastName: 'Hamadi', firstName: 'Ali', rank: 'OPL' },
  { lastName: 'Brahimi', firstName: 'Mohamed Amine', rank: 'OPL' },
  { lastName: 'Rahal', firstName: 'Zakaria', rank: 'OPL' },
  { lastName: 'Ahmed Boumaza', firstName: 'Mohamed El Mehdi', rank: 'OPL' },
  { lastName: 'Kerboub', firstName: 'Ahmed Sabri', rank: 'OPL' },
  { lastName: 'Boudermine', firstName: 'Mohamed', rank: 'OPL' },
  { lastName: 'Karrab', firstName: 'Radouane Nour El Hak', rank: 'OPL' },
  { lastName: 'Mechouma', firstName: 'Ayoub', rank: 'OPL' },
  { lastName: 'Achour', firstName: 'Adel', rank: 'OPL' },
  { lastName: 'Chabbia', firstName: 'Sofiane', rank: 'OPL' },
  { lastName: 'Sellal', firstName: 'Nour El Islam', rank: 'OPL' },
  { lastName: 'Touati', firstName: 'Anes Mohammed Walid', rank: 'OPL' },

  { lastName: 'Merabet', firstName: 'Sofiane', rank: 'OPL', licenseExpiry: '2026-07-31' },
  { lastName: 'Boumerdas', firstName: 'Abdelfetah', rank: 'OPL' },
  { lastName: 'Souiyou', firstName: 'Mouad', rank: 'OPL' },
  { lastName: 'Rouichedi', firstName: 'Younes', rank: 'OPL' },
  { lastName: 'Allame', firstName: 'Ilhem', rank: 'OPL' },
  { lastName: 'Hammou', firstName: 'Mohammed', rank: 'OPL' },
  { lastName: 'Ladaycia', firstName: 'Oussama', rank: 'OPL' },
  { lastName: 'Iberoualene', firstName: 'Fodil', rank: 'OPL' },
  { lastName: 'Louhbaibat', firstName: 'Mohamed El Amine', rank: 'OPL' },
  { lastName: 'Belhadad', firstName: 'Amine', rank: 'OPL' },
  { lastName: 'Allaoua', firstName: 'Hacene', rank: 'OPL' },
  { lastName: 'Aggoun', firstName: 'Walid', rank: 'OPL' },
  { lastName: 'Benabid', firstName: 'Samy-Adlane', rank: 'OPL' },
  { lastName: 'Bederina', firstName: 'Mohamed-Nazim', rank: 'OPL' },
  { lastName: 'Tounsi', firstName: 'Omar', rank: 'OPL' },
  { lastName: 'Kaddour', firstName: 'Nafaa', rank: 'OPL' },

  { lastName: 'Daoudi', firstName: 'Mohammed', rank: 'OPL' },
  { lastName: 'Daoud', firstName: 'Zakaria', rank: 'OPL' },
  { lastName: 'Farsi', firstName: 'Oussama', rank: 'OPL' },
  { lastName: 'Mahdid', firstName: 'Salim-Mehdi', rank: 'OPL' },
  { lastName: 'Nadir', firstName: 'Abderrahmane', rank: 'OPL' },
  { lastName: 'Boudiaf', firstName: 'Mohamed Hani', rank: 'OPL' },
  { lastName: 'Belfegas', firstName: 'Abdelbaki', rank: 'OPL' },
  { lastName: 'Hemchi', firstName: 'Oussama', rank: 'OPL', licenseExpiry: '2026-07-31' },
  { lastName: 'Dechmi', firstName: 'Amir', rank: 'OPL' },
  { lastName: 'Djedaimi', firstName: 'Arfane Hani', rank: 'OPL' },
  { lastName: 'Youcef', firstName: 'Sid-Ali', rank: 'OPL' },
  { lastName: 'Bouchakour', firstName: 'Ettayib', rank: 'OPL' },
  { lastName: 'Benloulou', firstName: 'Baba', rank: 'OPL' },
  { lastName: 'Medjahdi', firstName: 'Abdeldjalil', rank: 'OPL' },
  { lastName: 'Rebiai', firstName: 'Mohamed-El-Amine', rank: 'OPL' },
  { lastName: 'Mihoubi', firstName: 'Anis', rank: 'OPL' },
  { lastName: 'Baira', firstName: 'Youssouf-Baha-Eddine', rank: 'OPL' },
  { lastName: 'Kadri', firstName: 'Ahcene', rank: 'OPL' },
  { lastName: 'Taghane', firstName: 'Fares', rank: 'OPL' },
  { lastName: 'Saoud', firstName: 'Mohammed Chakib', rank: 'OPL' },
  { lastName: 'Benkhaled', firstName: 'Abdelhakim', rank: 'OPL', licenseExpiry: '2026-08-16' },
  { lastName: 'Bouchama', firstName: 'Abdelmounaim', rank: 'OPL' },
  { lastName: 'Zouiter', firstName: 'Ali', rank: 'OPL' },
  { lastName: 'Boureboune', firstName: 'Abdelhakim', rank: 'OPL' },
  { lastName: 'Aggoun', firstName: 'Fayçal', rank: 'OPL' },
  { lastName: 'Benbitour', firstName: 'Brahim', rank: 'OPL' },
  { lastName: 'Mekhezzem', firstName: 'Mohammed El-Amine', rank: 'OPL' },
  { lastName: 'Ould Babaali', firstName: 'Walid', rank: 'OPL' },
  { lastName: 'Belhadj', firstName: 'Mohamed Anes', rank: 'OPL' },
  { lastName: 'Haddadi', firstName: 'Zakaria', rank: 'OPL' },
  { lastName: 'Titi', firstName: 'Aymen', rank: 'OPL' },
  { lastName: 'Bouisri', firstName: 'Ahmed Djallel', rank: 'OPL' },
  { lastName: 'Kacha', firstName: 'Mohamed Mustapha', rank: 'OPL', licenseExpiry: '2026-08-06' },
  { lastName: 'Toubal', firstName: 'Abderrahmane', rank: 'OPL' },
  { lastName: 'Boularaf', firstName: 'Aissa', rank: 'OPL' },
  { lastName: 'Zerzouni', firstName: 'Billel', rank: 'OPL' },
  { lastName: 'Douag', firstName: 'Nanna Nardjes', rank: 'OPL', licenseExpiry: '2026-07-31' },
  { lastName: 'Bounib', firstName: 'Khaled', rank: 'OPL', licenseExpiry: '2026-08-23' },
  { lastName: 'Abdallah', firstName: 'Billel', rank: 'OPL' },
  { lastName: 'Delsi', firstName: 'Abdelmalek', rank: 'OPL' },
  { lastName: 'Haddadi', firstName: 'Mohammed', rank: 'OPL', licenseExpiry: '2026-08-17' },
  { lastName: 'Itou', firstName: 'Marouane', rank: 'OPL' },
  { lastName: 'Berrayah', firstName: 'Abdelnasser', rank: 'OPL' },

  { lastName: 'Mohamadi', firstName: 'Massinissa', rank: 'OPL' },
  { lastName: 'Mazouzi', firstName: 'Chouaib', rank: 'OPL' },
  { lastName: 'Aguida', firstName: 'Mohamed Amine', rank: 'OPL', licenseExpiry: '2026-08-30' },
  { lastName: 'Kaddouri', firstName: 'Mourad', rank: 'OPL' },
  { lastName: 'Bensahnoune', firstName: 'Bilal', rank: 'OPL' },
  { lastName: 'Bayou', firstName: 'Houssem', rank: 'OPL' },
  { lastName: 'Tayeb-Cherif', firstName: 'Nassim', rank: 'OPL' },
  { lastName: 'Benachour', firstName: 'Youcef', rank: 'OPL' },
  { lastName: 'Kartout', firstName: 'Abderrahmane', rank: 'OPL' },
  { lastName: 'Benaouda', firstName: 'Taha', rank: 'OPL' },
  { lastName: 'Djebloun', firstName: 'Abdelfattah', rank: 'OPL', licenseExpiry: '2026-07-31' },
  { lastName: 'Cherball', firstName: 'Lahcene', rank: 'OPL' },
  { lastName: 'Hentabli', firstName: 'Zaki', rank: 'OPL' },
  { lastName: 'Chehih', firstName: 'Meriem', rank: 'OPL' },
  { lastName: 'Saidani', firstName: 'Oussama', rank: 'OPL' },
  { lastName: 'Hallab', firstName: 'Redouane', rank: 'OPL' },
  { lastName: 'Ziada', firstName: 'Emir Adel', rank: 'OPL' },
  { lastName: 'Mahmoudi', firstName: 'Azeddine', rank: 'OPL' },
  { lastName: 'Elkerdi', firstName: 'Fayçal', rank: 'OPL' },
  { lastName: 'Rahou', firstName: 'Mohamed Zakaria', rank: 'OPL' },
  { lastName: 'Messaoudi', firstName: 'Mehdi Moundir', rank: 'OPL' },
  { lastName: 'Boubrit', firstName: 'Yanis', rank: 'OPL' },
  { lastName: 'Mitiche', firstName: 'Mohamed Hichem', rank: 'OPL' },
  { lastName: 'Lounis', firstName: 'Areski', rank: 'OPL' },
  { lastName: 'Manaa', firstName: 'Houcem Ahmed', rank: 'OPL' },
  { lastName: 'Ramoul', firstName: 'Abdenour', rank: 'OPL' },
  { lastName: 'Bensid', firstName: 'Abdallah Ramy', rank: 'OPL' },
  { lastName: 'Bennacer', firstName: 'Mehdi', rank: 'OPL' },
  { lastName: 'Tlemsani', firstName: 'Meriem', rank: 'OPL' },
  { lastName: 'Naidja', firstName: 'Nassim', rank: 'OPL' },
  { lastName: 'Ould Slimane', firstName: 'Ahmed Adel', rank: 'OPL' },
  { lastName: 'Kasri', firstName: 'Brahim Abdelhakim', rank: 'OPL' },
  { lastName: 'Benserhane', firstName: 'Mohamed El Hadi', rank: 'OPL' },
  { lastName: 'Hamamouche', firstName: 'Mohamed', rank: 'OPL' },
  { lastName: 'Nait Saada', firstName: 'Hamza', rank: 'OPL' },
  { lastName: 'Amira', firstName: 'Abdelkarim', rank: 'OPL' },
  { lastName: 'Haddaoui', firstName: 'Abderrazak Hani', rank: 'OPL' },
  { lastName: 'Krim', firstName: 'Rana', rank: 'OPL' },
  { lastName: 'Bencheikh', firstName: 'Raid', rank: 'OPL' },
  { lastName: 'Tabet', firstName: 'Anes', rank: 'OPL' },
  { lastName: 'Bettioui', firstName: 'Abdelmadjid Mohamed', rank: 'OPL' },
  { lastName: 'Medelci', firstName: 'Djezzar Fahd', rank: 'OPL' },
  { lastName: 'Djebrit', firstName: 'Abdelkader Riad', rank: 'OPL' },
  { lastName: 'Khechiba', firstName: 'Khaled', rank: 'OPL' },
  { lastName: 'Benouaret', firstName: 'Hamza', rank: 'OPL' },
  { lastName: 'Boulaouad', firstName: 'Med Amine', rank: 'OPL' },
  { lastName: 'Adane', firstName: 'Yasmine', rank: 'OPL' },
  { lastName: 'Benabbou', firstName: 'Ahmed Amine', rank: 'OPL' },

  { lastName: 'Mokhtari', firstName: 'Dalil', rank: 'OPL' },
  { lastName: 'Denideni', firstName: 'Lyes', rank: 'OPL' },
  { lastName: 'Chalabi', firstName: 'Bilel', rank: 'OPL' },
  { lastName: 'Merzougui', firstName: 'Med Amir', rank: 'OPL' },
  { lastName: 'Ahram', firstName: 'Chaker', rank: 'OPL' },
  { lastName: 'Zebboudj', firstName: 'Yanis', rank: 'OPL' },
  { lastName: 'Benziani', firstName: 'Aboulkecem', rank: 'OPL' },
  { lastName: 'Moustiri', firstName: 'Haroun', rank: 'OPL' },
  { lastName: 'Benhammou', firstName: 'Mokrane', rank: 'OPL' },
  { lastName: 'Charifi', firstName: 'Billel', rank: 'OPL' },
  { lastName: 'Gadoum', firstName: 'Merouane', rank: 'OPL', licenseExpiry: '2026-07-31' },
  { lastName: 'Boucenna', firstName: 'Sami', rank: 'OPL' },
  { lastName: 'Ferradji', firstName: 'Amine', rank: 'OPL' },
  { lastName: 'Hanafi', firstName: 'Mehdi', rank: 'OPL' },

  // Confirmés 737NG par le PDF SECTEUR_NG (licence déjà expirée/proche) alors
  // qu'ils n'avaient pas été repérés comme cochés sur la photo du classement FO.
  { lastName: 'Arab', firstName: 'Islam', rank: 'OPL', licenseExpiry: '2026-08-27' },
  { lastName: 'Bounar', firstName: 'Hichem', rank: 'OPL', licenseExpiry: '2026-08-30' },
  { lastName: 'Benali', firstName: 'Idir', rank: 'OPL', licenseExpiry: '2026-07-31' },
  { lastName: 'Brahimi', firstName: 'Ali', rank: 'OPL', licenseExpiry: '2026-07-31' }
];

export const SEED_PILOTS: SeedPilot[] = [...CAPTAINS, ...FIRST_OFFICERS];
