import type { PilotInput } from './db';

type SeedPilot = Pick<PilotInput, 'firstName' | 'lastName' | 'rank'>;

// Commandants de bord (CDB) 737NG — issus du classement professionnel définitif
// CDB année 2026 (pilotes cochés au stylo par Fleet Training).
const CAPTAINS: SeedPilot[] = [
  { lastName: 'Benbetka', firstName: 'Nadjib-Mohamed', rank: 'CDB' },
  { lastName: 'Bousmal', firstName: 'Zinedine', rank: 'CDB' },
  { lastName: 'Benseghir', firstName: 'Abdelkrim', rank: 'CDB' },
  { lastName: 'Hamza', firstName: 'Abdelmadjid', rank: 'CDB' },
  { lastName: 'Dakhli', firstName: 'Mahmoud', rank: 'CDB' },
  { lastName: 'Bachtarzi', firstName: 'Karim', rank: 'CDB' },
  { lastName: 'Teggari', firstName: 'Abdelwaheb', rank: 'CDB' },
  { lastName: 'Derouiche', firstName: 'Tarik-Rabah', rank: 'CDB' },
  { lastName: 'Bouachiba', firstName: 'Lakhdar', rank: 'CDB' },
  { lastName: 'Drider', firstName: 'Habib', rank: 'CDB' },
  { lastName: 'Bouhelassa', firstName: 'Abdelhafid', rank: 'CDB' },
  { lastName: 'Malki', firstName: 'Lounes', rank: 'CDB' },
  { lastName: 'Djoudi', firstName: 'Djamal', rank: 'CDB' },
  { lastName: 'Annane', firstName: 'Azeddine', rank: 'CDB' },

  { lastName: 'Laliki', firstName: 'Mohamed', rank: 'CDB' },
  { lastName: 'Zagai', firstName: 'Noureddine', rank: 'CDB' },
  { lastName: 'Chelli', firstName: 'Mouloud', rank: 'CDB' },
  { lastName: 'Bensaber', firstName: 'Amine-Mohamed', rank: 'CDB' },
  { lastName: 'Bouteflika', firstName: 'Sofiane-Mehdi', rank: 'CDB' },
  { lastName: 'Zerrouati', firstName: 'Abdelhakim', rank: 'CDB' },
  { lastName: 'Ounis', firstName: 'Malek', rank: 'CDB' },
  { lastName: 'Dabbagh', firstName: 'Firas', rank: 'CDB' },
  { lastName: 'Chelfaoui', firstName: 'Madjid', rank: 'CDB' },
  { lastName: 'Hasbellaoui', firstName: 'Raouf', rank: 'CDB' },
  { lastName: 'Iddir', firstName: 'Salem', rank: 'CDB' },
  { lastName: 'El-Amraoui', firstName: 'Khaled', rank: 'CDB' },
  { lastName: 'Zedmia', firstName: 'Maya-Djazia', rank: 'CDB' },
  { lastName: 'Miloudi', firstName: 'Mohamed-Islam', rank: 'CDB' },

  { lastName: 'Meraghni', firstName: 'Rabie', rank: 'CDB' },
  { lastName: 'Issiakhem', firstName: 'Karim-Thierry', rank: 'CDB' },
  { lastName: 'Boudiaf', firstName: 'Mehdi', rank: 'CDB' },
  { lastName: 'Chefirat', firstName: 'Karim', rank: 'CDB' },
  { lastName: 'Rebiai', firstName: 'Dounya', rank: 'CDB' },
  { lastName: 'Lazizi', firstName: 'Kamel', rank: 'CDB' },
  { lastName: 'Ben-Brahim', firstName: 'Mohamed', rank: 'CDB' },
  { lastName: 'Hadjadj-Aoul', firstName: 'Khalid', rank: 'CDB' },
  { lastName: 'Tebbi', firstName: 'Sabrina', rank: 'CDB' },
  { lastName: 'Laadjal', firstName: 'Radhia', rank: 'CDB' },
  { lastName: 'Kheddouci', firstName: 'Soufienne', rank: 'CDB' },
  { lastName: 'Bouchaita', firstName: 'Hocine', rank: 'CDB' },
  { lastName: 'Skander', firstName: 'Mohamed-Reda', rank: 'CDB' },
  { lastName: 'Ferr', firstName: 'Ilhem', rank: 'CDB' },
  { lastName: 'Bouchenafa', firstName: 'Mohamed-Amine', rank: 'CDB' },
  { lastName: 'Benzian', firstName: 'Tewfik-Fawzi', rank: 'CDB' },
  { lastName: 'Chelli', firstName: 'Hayet', rank: 'CDB' },
  { lastName: 'Derbal', firstName: 'Amine', rank: 'CDB' },
  { lastName: 'Larbi', firstName: 'Mohamed-Amine', rank: 'CDB' },
  { lastName: 'Gouaref', firstName: 'Hichem', rank: 'CDB' },
  { lastName: 'Oulmane', firstName: 'Tewfik', rank: 'CDB' },

  { lastName: 'Cherifi', firstName: 'Ouali-Zoheir', rank: 'CDB' },
  { lastName: 'Benasla', firstName: 'Tewfik', rank: 'CDB' },
  { lastName: 'Benbouaziz', firstName: 'Amine', rank: 'CDB' },
  { lastName: 'Annad', firstName: 'Yacine', rank: 'CDB' },
  { lastName: 'Terai', firstName: 'Sofiane', rank: 'CDB' },
  { lastName: 'Rebbouh', firstName: 'Mohamed-Amin', rank: 'CDB' },
  { lastName: 'Balit', firstName: 'Salim', rank: 'CDB' },
  { lastName: 'Ledjedel', firstName: 'Nassim', rank: 'CDB' },
  { lastName: 'Hanafi', firstName: 'Akram', rank: 'CDB' },
  { lastName: 'Abdelbaki', firstName: 'Dalil', rank: 'CDB' },
  { lastName: 'Atia', firstName: 'Oussama', rank: 'CDB' },
  { lastName: 'Mir', firstName: 'Abdellatif', rank: 'CDB' },
  { lastName: 'Driche', firstName: 'Mourad', rank: 'CDB' },
  { lastName: 'El-Amraoui', firstName: 'Tarek', rank: 'CDB' },
  { lastName: 'Zabchi', firstName: 'Yacine', rank: 'CDB' },
  { lastName: 'Guemari', firstName: 'Nissem', rank: 'CDB' },
  { lastName: 'Boukhalfa', firstName: 'Nacer-Eddine', rank: 'CDB' },
  { lastName: 'Otmane', firstName: 'Ahmed-Lyes', rank: 'CDB' },
  { lastName: 'Hamadouche', firstName: 'Mohamed-Nassim', rank: 'CDB' },
  { lastName: 'Ghezali', firstName: 'Ahmed', rank: 'CDB' },
  { lastName: 'Boutaleb', firstName: 'Abdelkader', rank: 'CDB' },
  { lastName: 'Aimeur', firstName: 'Mohamed-Lamine', rank: 'CDB' },
  { lastName: 'Atia', firstName: 'Zakaria', rank: 'CDB' },
  { lastName: 'Ferhat', firstName: 'Mahdi', rank: 'CDB' },
  { lastName: 'Hamici', firstName: 'Mounir', rank: 'CDB' },
  { lastName: 'Boukrif', firstName: 'Leila', rank: 'CDB' },
  { lastName: 'Moussaoui', firstName: 'Adel', rank: 'CDB' },
  { lastName: 'Boulanouar', firstName: 'Mohamed-Aboubakeur', rank: 'CDB' },
  { lastName: 'Aouissi', firstName: 'Melissa', rank: 'CDB' },
  { lastName: 'Mohammedi', firstName: 'Walid', rank: 'CDB' },
  { lastName: 'Besbaci', firstName: 'Mehdi', rank: 'CDB' },
  { lastName: 'Kermia', firstName: 'Yacine', rank: 'CDB' },
  { lastName: 'Hafiz', firstName: 'Sharif-Zerrouk', rank: 'CDB' },
  { lastName: 'Lalouani', firstName: 'Mohammed-El-Akram', rank: 'CDB' },
  { lastName: 'Houas', firstName: 'Riadh', rank: 'CDB' },
  { lastName: 'Benlalam', firstName: 'Hicham', rank: 'CDB' },
  { lastName: 'Saidi', firstName: 'Adel', rank: 'CDB' },
  { lastName: 'Berrazouane', firstName: 'Chafik', rank: 'CDB' },
  { lastName: 'Afif', firstName: 'Adel', rank: 'CDB' },
  { lastName: 'Bensenouci', firstName: 'Abdesselam-Fawzi', rank: 'CDB' },
  { lastName: 'Metref', firstName: 'Mounir', rank: 'CDB' },
  { lastName: 'Benbouali', firstName: 'Ryad', rank: 'CDB' },
  { lastName: 'Touimer', firstName: 'Mohamed', rank: 'CDB' },
  { lastName: 'Rekibi', firstName: 'Seddik', rank: 'CDB' },
  { lastName: 'Berkani', firstName: 'Ali', rank: 'CDB' },
  { lastName: 'Mezimez', firstName: 'Messaouda', rank: 'CDB' },
  { lastName: 'Bouziri', firstName: 'Feryal-Fifi', rank: 'CDB' },
  { lastName: 'Boubekeur', firstName: 'Yacine', rank: 'CDB' },

  { lastName: 'Benouis', firstName: 'Mohammed-Fethi', rank: 'CDB' },
  { lastName: 'Terki', firstName: 'Omar-Nabil', rank: 'CDB' },
  { lastName: 'Benmiloud', firstName: 'Amine', rank: 'CDB' },
  { lastName: 'Belkham', firstName: 'Adel', rank: 'CDB' },
  { lastName: 'Aroua', firstName: 'Mohamed-Bilal', rank: 'CDB' },
  { lastName: 'Medkour', firstName: 'Elmoatassem', rank: 'CDB' },
  { lastName: 'Doumi', firstName: 'Youssef-Karim', rank: 'CDB' },
  { lastName: 'Hammoudi', firstName: 'Karim', rank: 'CDB' },
  { lastName: 'Trabzi', firstName: 'Mohamed', rank: 'CDB' },
  { lastName: 'Bouras', firstName: 'Mansour', rank: 'CDB' },
  { lastName: 'Bourradou', firstName: 'Redouane', rank: 'CDB' },
  { lastName: 'Ghobrini', firstName: 'Abdelghani', rank: 'CDB' },
  { lastName: 'Djermani', firstName: 'Mounir', rank: 'CDB' },
  { lastName: 'Chebout', firstName: 'Salim', rank: 'CDB' },
  { lastName: 'Mehenni', firstName: 'Feriel', rank: 'CDB' },
  { lastName: 'Daoud', firstName: 'Mohamed-Amine', rank: 'CDB' },
  { lastName: 'Rahal', firstName: 'Hadi-Aniss', rank: 'CDB' },
  { lastName: 'Bousbah', firstName: 'Abdelkrim', rank: 'CDB' },
  { lastName: 'Diafat', firstName: 'Abdelkader', rank: 'CDB' },
  { lastName: 'Arifi', firstName: 'Oussama', rank: 'CDB' },
  { lastName: 'Meziani', firstName: 'Mouloud', rank: 'CDB' },
  { lastName: 'Orif', firstName: 'Rachid', rank: 'CDB' },
  { lastName: 'Bidi', firstName: "M'Hamed", rank: 'CDB' },
  { lastName: 'Amira', firstName: 'Chakib', rank: 'CDB' },
  { lastName: 'Aliouèche', firstName: 'Nacim', rank: 'CDB' },
  { lastName: 'Sahli', firstName: 'Youcef', rank: 'CDB' },
  { lastName: 'Semidaa', firstName: 'Yacine', rank: 'CDB' },
  { lastName: 'Arroudj', firstName: 'Ali-Sabri', rank: 'CDB' },
  { lastName: 'Bekralas', firstName: 'Cherine', rank: 'CDB' },
  { lastName: 'Belkacem', firstName: 'Mohamed-Tewfik', rank: 'CDB' },
  { lastName: 'Mesloub', firstName: 'Khelifa-Tarik', rank: 'CDB' },
  { lastName: 'Lounis', firstName: 'Abdesselem', rank: 'CDB' },
  { lastName: 'Missaoui', firstName: 'Ala-Eddine', rank: 'CDB' },
  { lastName: 'Chachoua', firstName: 'Mohamed-Riadh', rank: 'CDB' },
  { lastName: 'Saidi', firstName: 'Sofiane', rank: 'CDB' },
  { lastName: 'Mesli', firstName: 'Mohamed-Riadh', rank: 'CDB' },
  { lastName: 'Ait-Hamou', firstName: 'Yougourthene', rank: 'CDB' },
  { lastName: 'Benhama', firstName: 'Yacine', rank: 'CDB' },
  { lastName: 'Azzouz', firstName: 'Mounir', rank: 'CDB' },
  { lastName: 'Sahnoun', firstName: 'Mohamed-Islam', rank: 'CDB' },
  { lastName: 'Tifoura', firstName: 'Mohamed', rank: 'CDB' },
  { lastName: 'Hamdi-Pacha', firstName: 'Madih', rank: 'CDB' },
  { lastName: 'Abbout', firstName: 'Hilal', rank: 'CDB' },
  { lastName: 'Akli', firstName: 'Fahim', rank: 'CDB' },
  { lastName: 'Braham-Chaouche', firstName: 'Salim', rank: 'CDB' },
  { lastName: 'Benbouaziz', firstName: 'Samy', rank: 'CDB' },
  { lastName: 'Saadouni', firstName: 'Faiz', rank: 'CDB' },
  { lastName: 'Medjamia', firstName: 'Smail', rank: 'CDB' },

  { lastName: 'Nacer-Bey', firstName: 'Mahrez', rank: 'CDB' },
  { lastName: 'Akrour', firstName: 'Zineb', rank: 'CDB' },
  { lastName: 'Bensadi', firstName: 'Redouane', rank: 'CDB' },
  { lastName: 'Khelifa', firstName: 'Sofiane', rank: 'CDB' },
  { lastName: 'Dib', firstName: 'Lotfi', rank: 'CDB' },
  { lastName: 'Ouaguenouni', firstName: 'Amine El-Mahdi', rank: 'CDB' },
  { lastName: 'Benmansour', firstName: 'Lahcene-Riad', rank: 'CDB' },
  { lastName: 'Lamdjadani', firstName: 'Sarah-Loubna', rank: 'CDB' },
  { lastName: 'Lekkal', firstName: 'Mehdi-Redouane', rank: 'CDB' },
  { lastName: 'Rida', firstName: 'Badis', rank: 'CDB' },
  { lastName: 'Saidane', firstName: 'Khalil', rank: 'CDB' },
  { lastName: 'Hachemi', firstName: 'Amir', rank: 'CDB' },
  { lastName: 'Messad', firstName: 'Amir-Khane', rank: 'CDB' },
  { lastName: 'Mokrane', firstName: 'Mohamed-Cherif', rank: 'CDB' },
  { lastName: 'Aggoun', firstName: 'Ahmed-Kheireddine', rank: 'CDB' },
  { lastName: 'Bencharif', firstName: 'Yacine-Reza', rank: 'CDB' },
  { lastName: 'Hadj-Mehdi', firstName: 'Samy', rank: 'CDB' },
  { lastName: 'Tobni', firstName: 'Mohamed Amine', rank: 'CDB' },
  { lastName: 'Rechache', firstName: 'Abdelhamid', rank: 'CDB' },
  { lastName: 'Hachouf', firstName: 'Mohamed Amine', rank: 'CDB' },
  { lastName: 'Graine', firstName: 'Mohammed Amine', rank: 'CDB' },
  { lastName: 'Boucenna', firstName: 'Riadh', rank: 'CDB' },
  { lastName: 'Boucenna', firstName: 'Lyes', rank: 'CDB' },

  { lastName: 'Ramdane', firstName: 'Sofiane', rank: 'CDB' }
];

// Les officiers pilotes de ligne (OPL) seront ajoutés ici une fois la liste
// transmise par Fleet Training.
const FIRST_OFFICERS: SeedPilot[] = [];

export const SEED_PILOTS: SeedPilot[] = [...CAPTAINS, ...FIRST_OFFICERS];
